name: docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up docker build
        uses: docker/setup-buildx-action@v2.0.0

      - name: download a build artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: api-go

      - name: docker login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_LOGIN_USER }}
          password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_LOGIN_USER }}/go_ci:${{  github.ref_name }}
